// commons/module-loader-vue/src/module-loader.vue
<template>
  <div :id="`render-${ entry }`" ref="mount"></div>
</template>

<script>
import { moduleLoader } from 'module-loader';

export default {
  props: [ 'src', 'entry', 'events' ],
  data() {
    return { moduleUnloader: null };
  },
  mounted() {
    this.moduleUnloader = moduleLoader({
      src: this.src,
      entry: this.entry,
      events: this.events,
      mount: this.$refs.mount,
      pushState: (href) => this.$emit('pushState', href)
    });
  },
  beforeDestroy() {
    this.moduleUnloader?.();
  }
}
</script>

// commons/module-loader-svelte/src/module-loader.svelte
<script>
import { onDestroy, createEventDispatcher } from 'svelte';
import { moduleLoader } from 'module-loader';

export let src;
export let entry;
export let events;
let mount;

const dispatch = createEventDispatcher();

let moduleUnloader = moduleLoader({
  src,
  entry,
  events,
  mount,
  pushState: (href) => dispatch('pushState', href)
});

onDestroy(() => {
  moduleUnloader && moduleUnloader();
});
</script>

<div id={`render-${ entry }`} bind:this={mount}></div>
